CREATE TABLE Users
(
	EmailAddress VARCHAR(320) NOT NULL PRIMARY KEY,
	Name VARCHAR(50) NOT NULL,
	PictureURL VARCHAR(255) NOT NULL
	PasswordHash VARCHAR(300) NOT NULL
	UserType BIT NOT NULL
)

CREATE TABLE Listings 
(
	ListingID int IDENTITY(1,1) PRIMARY KEY,
	Title VARCHAR(255) NOT NULL,
	BookName VARCHAR(255) NOT NULL,
	CoverImageURL VARCHAR(255) NOT NULL,
	Condition VARCHAR(50) NOT NULL,
	Price VARCHAR(50) NOT NULL,
	ListingDescription VARCHAR(1000),
	PostingDate DATETIME NOT NULL,
	EmailAddress VARCHAR(320) NOT NULL FOREIGN KEY REFERENCES Users(EmailAddress)
)